name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
        architecture: x64
    - run: pip install nox
    - run: pip install poetry
    - run: nox
    - uses: actions/upload-artifact@v3
      with:
        name: pytest-resul-3.8
        path: test-result-3.8.xml
      if: ${{ always() }}